### ISSUE TITLE
Error: Call to undefined method RepoGroup::singleton() on rebuldData.php

### ISSUE THREAD

**Issue by krabina** [ProfessionalWiki/ModernTimeline#33]
### Setup

- MW version: 1.39.5
- PHP version: 7.4.33
- DB (MySQL etc.): 8.0.28
- SMW version: 4.2.1
- MT version: 1.2.1
- Browsers and versions (if applicable):

### Issue

When running rebuildData.php the following error is shown (on some pages using MT)

**Stacktrace** 

```
[82f9c371fea7fceb024147c5] [no req]   Error: Call to undefined method RepoGroup::singleton()
Backtrace:
from /extensions/ModernTimeline/src/EventExtractor.php(60)
#0 /extensions/ModernTimeline/src/EventExtractor.php(39): ModernTimeline\EventExtractor->getUrlForFileTitle()
#1 /extensions/ModernTimeline/src/TimelinePresenter.php(40): ModernTimeline\EventExtractor->extractEvents()
#2 /extensions/ModernTimeline/src/TimelinePresenter.php(32): ModernTimeline\TimelinePresenter->createJsonString()
#3 /extensions/ModernTimeline/src/ModernTimelinePrinter.php(61): ModernTimeline\TimelinePresenter->presentResult()
#4 /extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(348): ModernTimeline\ModernTimelinePrinter->getResult()
#5 /extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(370): SMWQueryProcessor::getResultFromQuery()
#6 /extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(202): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters()
#7 /extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(402): SMW\ParserFunctions\AskParserFunction->parse()
#8 /includes/parser/Parser.php(3437): SMW\ParserFunctionFactory->SMW\{closure}()
#9 /includes/parser/Parser.php(3122): Parser->callParserFunction()
#10 /includes/parser/PPFrame_Hash.php(275): Parser->braceSubstitution()
#11 /includes/parser/Parser.php(2951): PPFrame_Hash->expand()
#12 /includes/parser/Parser.php(1609): Parser->replaceVariables()
#13 /includes/parser/Parser.php(723): Parser->internalParse()
#14 /includes/content/WikitextContentHandler.php(301): Parser->parse()
#15 /includes/content/ContentHandler.php(1721): WikitextContentHandler->fillParserOutput()
#16 /includes/content/Renderer/ContentRenderer.php(47): ContentHandler->getParserOutput()
#17 /extensions/SemanticMediaWiki/includes/ContentParser.php(168): MediaWiki\Content\Renderer\ContentRenderer->getParserOutput()
#18 /extensions/SemanticMediaWiki/includes/ContentParser.php(130): SMW\ContentParser->fetchFromContent()
#19 /extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(199): SMW\ContentParser->parse()
#20 /extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(139): SMW\MediaWiki\Jobs\UpdateJob->parse_content()
#21 /extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(94): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#22 /extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(247): SMW\MediaWiki\Jobs\UpdateJob->run()
#23 /extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(472): SMW\SQLStore\Rebuilder\Rebuilder->rebuild()
#24 /extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(385): SMW\Maintenance\DataRebuilder->doUpdateById()
#25 /extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(224): SMW\Maintenance\DataRebuilder->rebuildAll()
#26 /extensions/SemanticMediaWiki/maintenance/rebuildData.php(198): SMW\Maintenance\DataRebuilder->rebuild()
#27 /maintenance/includes/MaintenanceRunner.php(309): SMW\Maintenance\rebuildData->execute()
#28 /maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#29 /extensions/SemanticMediaWiki/maintenance/rebuildData.php(294): require_once(string)
#30 {main}

```
rebuild does not continue even though --ignore-exceptions is set. Had to manually skip the affected ids.

**Comment by krabina** [comment]
https://github.com/ProfessionalWiki/ModernTimeline/blob/cf9b3ddc2bda00972d159852e5e2a4fc318b365e/src/EventExtractor.php#L65

**Comment by krabina** [comment]
Was a breaking change in 1.38: https://www.mediawiki.org/wiki/Release_notes/1.38

**Comment by thomas-topway-it** [comment]
@krabina fixed in master https://github.com/ProfessionalWiki/ModernTimeline/blob/cf9b3ddc2bda00972d159852e5e2a4fc318b365e/src/EventExtractor.php
